local assert = require("luassert")
local helper = require("tests.helpers.subprocess")
local controllers = require("neoagent.process_sessions.local")

describe("local retained process admission", function()
  it("releases a revoked constructor and rejects startup and control without native allocation", function()
    local controller = controllers.new(helper.spec("unused"), 64)
    assert.is_false(controller:state().released)
    controller:dispose("admission revoked")
    assert.is_true(controller:state().done)
    assert.is_true(controller:state().released)
    assert.is_true(helper.complete(function() return controller:wait() end))
    local started = helper.complete(function() return controller:start() end)
    assert.are.equal("process_disposed", assert(started.error).code)
    local written = helper.complete(function() return controller:control({ kind = "write", data = "unused" }) end)
    assert.are.equal("process_disposed", assert(written.error).code)
  end)
end)
