local truncate = require("neoagent.tools.truncate")

describe("neoagent.tools.truncate", function()
  it("keeps complete lines from the head", function()
    local result = truncate.head("one\ntwo\nthree", { max_lines = 2, max_bytes = 100 })
    assert.are.equal("one\ntwo", result.content)
    assert.are.equal("lines", result.truncatedBy)
    assert.are.equal(3, result.totalLines)
  end)

  it("does not return a partial first line", function()
    local result = truncate.head("abcdef\nnext", { max_lines = 10, max_bytes = 3 })
    assert.are.equal("", result.content)
    assert.is_true(result.firstLineExceedsLimit)
  end)

  it("keeps the tail and a valid UTF-8 boundary", function()
    local result = truncate.tail("first\nsecond\nthird", { max_lines = 2, max_bytes = 100 })
    assert.are.equal("second\nthird", result.content)
    local partial = truncate.tail("ééé", { max_lines = 1, max_bytes = 3 })
    assert.are.equal("é", partial.content)
    assert.is_true(partial.lastLinePartial)
  end)

  it("shortens individual grep lines", function()
    local value, changed = truncate.line("abcdef", 3)
    assert.are.equal("abc... [truncated]", value)
    assert.is_true(changed)
    assert.are.same({ "short", false }, { truncate.line("short", 5) })
  end)

  it("reports byte truncation and human-readable sizes", function()
    local result = truncate.head("aa\nbbbb", { max_lines = 10, max_bytes = 3 })
    assert.are.equal("aa", result.content)
    assert.are.equal("bytes", result.truncatedBy)
    assert.are.equal(1, truncate.head("one\n", { max_lines = 10, max_bytes = 10 }).totalLines)
    assert.are.equal("10B", truncate.format_size(10))
    assert.are.equal("1.0KB", truncate.format_size(1024))
    assert.are.equal("1.0MB", truncate.format_size(1024 * 1024))
  end)
end)
